ERROR_RESPONSE_STATUS = "ERROR - unhealthy"
ISERROR_RESPONSE_CODE = 500
FILE_NOT_FOUND = "DB NOT FOUND"

OK_RESPONSE_STATUS = "OK - healthy"
OK_RESPONSE_CODE = 200
FILE_FOUND = "DB PRESENT"

APPLICATION_CONTENT_TYPE = "application/json"

DB_CONNECTION_STRING = 'file:techtrends.db?mode=rw'
DB_NAME = 'techtrends.db'
POSTS_COUNT = 0
DB_CONNECTION_COUNT = 0
