##  Named of the workflow.
name: TechTrends - Package with Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branchon:
on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]
    tags:
      - "v*.*.*"

## List the steps to be executed by the workflow
jobs:
  ## Set the name of the job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.8]
    ## Define a sequence of steps to be executed
    steps:
      ## Use the public `checkout` action  in version v2
      ## to checkout the existing code in the repository
      - uses: actions/checkout@v2

        ## Use the public `setup-python` actoin  in version v2
        ## to install python on the Ubuntu based environment.
        ## Additionally, it ensures to loop through all
        ## the defined Python versions.
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

        ## Install all necessary dependecies .
        ## For example any defined packages within the requirements.txt file.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        ## Setting up Docker QEMU Support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

        ##  Docker CLI plugin that provides enhanced build capabilities.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

        ## log in to docker hub with authenticated tokens
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        ## Docker metadata
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/techtrends
          tags: |
            type=semver,pattern={{ raw }}
            type=semver,pattern={{ raw }},value=v1.0.0

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/techtrends:latest
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cach
